### ISSUE TITLE
auth bypass key + discord

### ISSUE THREAD

**Issue by vaodaa** [call-042PE/call-042PE#1]
Salut jai vue que tu etait francais esque Cracked key  bypass marche toujours ou pas et Yaurais moyen si t'aurais un groupe discord pour parler ?? un truck comme sa :) ps: mon discord Vaoda#1021

**Comment by vaodaa** [comment]
![image](https://user-images.githubusercontent.com/59312266/99902242-9af2a880-2cbc-11eb-83b6-b19b26705401 Sa ne fait que sa en boucle :/

**Comment by vaodaa** [comment]
![Capture](https://user-images.githubusercontent.com/59312266/99902274-dbeabd00-2cbc-11eb-94af-93b97aefef9e.PNG)
Sa ne fait que sa en boucle :/

**Comment by vaodaa** [comment]
Et jai essaye avec how to get secret key mais jai tjr pas trouver si tu pourrais m'aider :)

**Comment by call-042PE** [comment]
Tu ne doit pas avoir python d'installer ou d'ajouter au path

**Comment by vaodaa** [comment]
Oui jai regarde les autres reponse et jai bien tout + le certifcat installer

**Comment by vaodaa** [comment]
Tu aurais un discord ?

**Comment by vaodaa** [comment]
https://cracked.to/Thread-Supreme-Cracked-PrimeKiller-MultiChecker Je te laisse essayer et dit moi si c que moi

**Comment by vaodaa** [comment]
![Capture](https://user-images.githubusercontent.com/59312266/99904062-ea3ed600-2cc8-11eb-9893-5cebde00088e.PNG)

**Comment by call-042PE** [comment]
C'est que toi quand tu tape python sur un cmd que as tu ?

**Comment by vaodaa** [comment]
Oui

**Comment by vaodaa** [comment]
![Uploading ezgif.com-gif-maker.gif…]()

**Comment by vaodaa** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/59312266/99904360-acdb4800-2cca-11eb-957b-2d3000f358a7.gif)

**Comment by vaodaa** [comment]
Alors Quesque tu en pense ??

**Comment by vaodaa** [comment]
> C'est que toi quand tu tape python sur un cmd que as tu ?

Si t'arrive a m'aider sa serais sympa :/

**Comment by vaodaa** [comment]
Update : J'ai toujours pas réussis a trouver le auth key même en essayant les checkers que ta mis ici https://github.com/call-042PE/Mephistopheles-SecretKey/blob/master/secretkey.txt et en suivant aussi les video pour trouver les keys mais rien ne marche donc jsp si c les forums qui on changer leur systems de AUTH ou c juste moi ..

**Comment by vaodaa** [comment]
Si tu pouvais voir c'est quoi le probleme et si on pourrais parler sur discord mon discord : Vaoda#1021 Merci et je te félicite pour ton boulot psk faire sa chapeaux car sa serais tellement utle dommage ..
